# Generated by Django 5.0.7 on 2024-08-09 22:23

import chat.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_remove_user_thumbnail_user_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to=chat.models.upload_thumbnail),
        ),
    ]
